apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cm9vdA==  # base64 encoded 'root'
  POSTGRES_PASSWORD: cm9vdA==  # base64 encoded 'root'
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=  # base64 encoded 'admin@example.com'
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=  # base64 encoded 'admin'