replicaCount: 1

image:
  repository: ciulik/postgres-go-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  image: postgres:latest
  db: mydb
  host: postgres
  servicePort: "5432"

pgadmin:
  image: dpage/pgadmin4:latest
  serviceType: LoadBalancer
  servicePort: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
