replicaCount: 1

image:
  repository: ciulik/postgres-go-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  image: postgres:latest
  user: root
  password: root
  db: mydb
  servicePort: 5432

pgadmin:
  image: dpage/pgadmin4:latest
  email: admin@example.com
  password: admin
  serviceType: LoadBalancer
  servicePort: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
