promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.loki-stack:3100/loki/api/v1/push
    scrape_configs:
      - job_name: pogo-app
        static_configs:
          - targets:
              - localhost
            labels:
              job: pogo-app
              __path__: /var/log/containers/*pogo-app*.log
