loki:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.monitoring:3100/loki/api/v1/push
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.monitoring:3100
          isDefault: true
