services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - assembly-docker_default
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - assembly-docker_default
    ports:
      - "80:80"
    depends_on:
      - db

  goapp:
    container_name: pogo_main
    image: ciulik/postgres-go-app:1.0
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mydb
      DB_HOST: postgres_container
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - assembly-docker_default

volumes:
  db-data:

networks:
  assembly-docker_default:
    external: false