apiVersion: apps/v1
kind: Deployment
metadata:
  name: pogo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pogo
  template:
    metadata:
      labels:
        app: pogo
    spec:
      containers:
        - name: pogo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: {{ .Values.postgres.db }}
            - name: DB_HOST
              value: {{ .Values.postgres.host }}
            - name: DB_PORT
              value: {{ .Values.postgres.servicePort }}
