apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: {{ .Values.pgadmin.serviceType }}
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: {{ .Values.pgadmin.servicePort }}
      targetPort: 80
